_target_: mpinv.models.mlp.MLP
cfg:
  _target_: mpinv.models.mlp.MLPConfig
  input_dim: ???
  output_dim: ???
  hidden_size: 512
  hidden_size_min: 32
  n_hidden_layers: 5
  architecture: bottleneck
  dropout: 0.0
  use_layer_norm: true
  use_bias: true
  activation: silu
