"""Base ``Callback`` class with no-op defaults for every hook."""

from __future__ import annotations

from typing import Any


class Callback:
    """Trainer callback. Override the hooks you need; defaults are no-ops.

    The ``ctx`` argument is a :class:`mpinv.training.trainer.TrainingContext` —
    a mutable container with the current state (model, optimiser, loss, batch,
    epoch counter, step counter, last metrics, ...).
    """

    def on_fit_start(self, ctx: Any) -> None: ...
    def on_epoch_start(self, ctx: Any) -> None: ...
    def on_batch_start(self, ctx: Any) -> None: ...
    def on_forward_end(self, ctx: Any) -> None: ...
    def on_loss_end(self, ctx: Any) -> None: ...
    def on_backward_end(self, ctx: Any) -> None: ...
    def on_step_end(self, ctx: Any) -> None: ...
    def on_batch_end(self, ctx: Any) -> None: ...
    def on_epoch_end(self, ctx: Any) -> None: ...
    def on_validation_end(self, ctx: Any) -> None: ...
    def on_fit_end(self, ctx: Any, status: str = "FINISHED") -> None: ...
